### ISSUE TITLE
Wrong displayed

### ISSUE THREAD

**Issue by robmroi** [rfeoi/4-Gewinnt#2]
When you play against the computer, it always says "computer ist am Zug" (computers turn)

**Comment by strifel** [comment]
Commit 1284b026ea18e419ba263ca7146dc4fae33b1a74 : Fixed this
Now it always says "Spieler 1 ist am Zug" (Its player 1's turn), this comes because computer is directly after player playing (so it is rewritten directly)

I will close this issue
