### ISSUE TITLE
AI sets in every row

### ISSUE THREAD

**Issue by robmroi** [rfeoi/4-Gewinnt#5]
When playing with the AI, the AI should set in every row and delete it after that. But it does not delete it.
<img width="549" alt="bildschirmfoto 2018-09-27 um 15 58 09" src="https://user-images.githubusercontent.com/24611970/46151100-5438cd80-c26e-11e8-91b6-fa748afd50f5.png">

**Comment by strifel** [comment]
Fixed this with Commit 922228f4508b9fd8932aaa67b443ccc8e7e22161
Array was not copied (and wrong copied). Fixed the reference.
